services:
  springboot:
    build: ./services/decision-engine
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
    environment:
      - AI_SERVICE_URL=http://fastapi:8000
    networks:
      - app-network
    restart: always
    container_name: springboot
  fastapi:
    build: ./services/ai-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always
    container_name: fastapi

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - springboot
    networks:
      - app-network
    restart: always
    container_name: frontend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - fastapi
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - app-network
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

networks:
  app-network:
    driver: bridge
